### ISSUE TITLE
Pre-trained Model Not Loading Correctly

### ISSUE THREAD

**Issue by MrWeast** [G-Taxonomy-Workgroup/GPSE#1] opened 2023-11-26 10:58 UTC
## Description:

When following the example instructions to run a pretrained model it fails due to size mismatching in various layers

#### Reproduction Steps:
1. Get the Pre-trained on MolPCBA (default)

- wget https://zenodo.org/record/8145095/files/gpse_model_molpcba_1.0.pt -O pretrained_models/gpse_molpcba.pt

2. run down stream evaluations
- python main.py --cfg configs/mol_bench/zinc-GPS+GPSE.yaml

## Environment:
- Operating System: Windows 10

## Code Snippets:
```
RuntimeError: Error(s) in loading state_dict for GraphGymModule:
        size mismatch for model.post_mp.node_post_mps.0.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.0.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.0.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.1.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.1.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.1.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.2.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.2.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.2.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.3.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.3.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.3.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.4.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.4.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.4.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.5.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.5.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.5.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.6.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.6.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.6.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.7.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.7.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.7.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.8.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.8.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.8.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.9.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.9.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.9.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.10.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.10.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.10.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.11.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.11.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.11.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.12.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.12.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.12.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.13.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.13.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.13.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.14.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.14.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.14.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.15.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.15.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.15.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.16.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.16.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.16.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.17.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.17.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.17.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.18.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.18.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.18.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.19.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.19.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.19.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.20.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.20.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.20.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.21.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.21.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.21.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.22.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.22.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.22.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.23.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.23.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.23.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.24.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.24.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.24.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.25.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.25.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.25.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.26.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.26.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.26.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.27.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.27.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.27.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.28.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.28.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.28.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.29.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.29.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.29.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.30.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.30.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.30.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.31.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.31.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.31.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.32.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.32.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.32.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.33.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.33.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.33.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.34.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.34.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.34.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.35.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.35.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.35.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.36.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.36.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.36.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.37.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.37.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.37.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.38.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.38.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.38.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.39.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.39.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.39.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.40.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.40.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.40.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.41.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.41.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.41.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.42.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.42.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.42.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.43.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.43.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.43.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.44.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.44.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.44.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.45.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.45.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.45.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.46.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.46.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.46.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.47.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.47.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.47.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.48.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.48.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.48.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.49.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.49.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.49.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
        size mismatch for model.post_mp.node_post_mps.50.model.0.Layer_0.layer.model.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for model.post_mp.node_post_mps.50.model.0.Layer_0.layer.model.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for model.post_mp.node_post_mps.50.model.1.model.weight: copying a param with shape torch.Size([1, 32]) from checkpoint, the shape in current model is torch.Size([1, 512]).
```

**Comment by semihcanturk** [comment] 2023-11-26 23:07
Hi @MrWeast, thanks for reaching out! I just tested by setting the repo from scratch, and the pretrained weights *should* work fine. I suspect some package versions might be messing things up here. 

Did you follow the installation instructions listed in the README? If some package versions are different, could you add your Python version as well as package versions for PyTorch (`torch`) and PyG (`torch-geometric`) ?

**Comment by MrWeast** [comment] 2023-11-27 00:38
I followed the install instructions as well and didn't get any errors for any of the dependencies. But I was looking at the documentation for some of the dependencies and saw that pyg-lib is not supported on windows so I suspect that is the issue. 

When I get a chance I'll check what versions I'm running for PyTorch and PyTorch-geometric. Also I'll create an Ubuntu VM and try everything again to see if the issue persists.

**Comment by RemyLau** [comment] 2023-11-27 17:42
`pyg-lib` might be indeed unnecessary. Another thing to check is whether you have installed a newer version of `pyg` (the latest version is [2.4.0](https://github.com/pyg-team/pytorch_geometric/releases/tag/2.4.0), which will be installed instead of *intended version* 2.2 if you did not explicitly specified the version as instructed in the README). I will also do a test myself using pyg 2.4 and see if I get this error.

A little bit more info about this error: This is due to a dimension mismatch of the PSE prediction head MLPs. Each of these MLPs project the hidden representation of a node to the predicted PSE for that node (for graph-level PSEs, we apply a sum pooling first). The hidden dimension of the MLP is specified as 32 in our GPSE recipe (see [this line](https://github.com/G-Taxonomy-Workgroup/GPSE/blob/1274d7e1bb78d8ff1e1948da53310d8f2e90deef/configs/mol_bench/zinc-GPS%2BGPSE.yaml#L44C20-L44C20) of the zinc-GPS+GPSE config file you referred to). The error was due to the actual dimension for the GPSE model initialized have 512 hidden dimensions in the final MLPs. This is unexpected due to our explicit specification of the prediction MLP with 32 hidden dimensions. I will do more investigation and see where this mismatch occurs.

**Comment by MrWeast** [comment] 2023-11-28 03:52
More information about my environment: 
pyg version 2.4.0     
pytorch version 1.12.1

I will also try again with the correct pyg version and see if the issue persists

**Comment by RemyLau** [comment] 2023-11-29 20:05
Ok I can confirm that the issue was indeed due to PyG 2.4. If you install PyG 2.2, you should be able to run with no issue.

I will do a little more investigation and see if the cause of this incompatibility.

[update] Found the bug in the graphgym module in PyG 2.4. It was due to incorrect handeling of MLP config (https://github.com/pyg-team/pytorch_geometric/issues/8484). So, for now, please do not use PyG 2.4.0. Any version in between 2.2 (inclusive) and 2.4.0 (exclusive) should be ok.

**Comment by RemyLau** [comment] 2023-11-30 15:48
I have pushed a hotfix to this (https://github.com/pyg-team/pytorch_geometric/pull/8486), and the next patch release of PyG (2.4.1?) should fix this issue.

**Comment by RemyLau** [comment] 2023-12-04 00:15
Closing this since the issue should be resolved. But please feel free to reopen or comment if you have any questions or issues related to this thread!

**Closed as completed by RemyLau** 2023-12-04 00:15 UTC
